# Generated by Django 3.1.5 on 2021-01-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nama',
            new_name='name',
        ),
    ]
