# Generated by Django 3.1.5 on 2021-01-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210130_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('icon', models.ImageField(upload_to='')),
                ('url', models.SlugField()),
                ('status', models.IntegerField(choices=[(0, 'Non Aktif'), (1, 'Aktif')])),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
        ),
    ]
