# Generated by Django 2.2.7 on 2021-01-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeakun', models.CharField(max_length=20, verbose_name='Kode*')),
                ('namaakun', models.CharField(max_length=50, verbose_name='Nama*')),
                ('tabelbantuan', models.CharField(max_length=20, verbose_name='Tabel*')),
                ('possaldo', models.CharField(max_length=50, verbose_name='PosSaldo*')),
                ('saldoawal', models.CharField(max_length=50, verbose_name='SaldoAwal*')),
                ('aktif', models.BooleanField(verbose_name='Aktif*')),
            ],
        ),
    ]
