# Generated by Django 2.2.7 on 2021-01-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20210111_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='possaldo',
            field=models.IntegerField(choices=[('debet', 'Debet'), ('kredit', 'Kredit')], verbose_name='PosSaldo*'),
        ),
    ]
