# Generated by Django 2.2.7 on 2021-01-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20210111_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='poslaporan',
            field=models.IntegerField(choices=[('debet', 'DEBET'), ('kredit', 'KREDIT')], default=1101, verbose_name='Pos Laporan*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='akun',
            name='possaldo',
            field=models.IntegerField(choices=[('debet', 'DEBET'), ('kredit', 'KREDIT')], verbose_name='Pos Saldo*'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='saldoawal',
            field=models.CharField(max_length=50, verbose_name='Saldo Awal*'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='tabelbantuan',
            field=models.CharField(max_length=20, verbose_name='Tabel Bantuan*'),
        ),
    ]
