# Generated by Django 2.2.7 on 2021-01-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20210111_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='poslaporan',
            field=models.IntegerField(choices=[('neraca', 'NERACA'), ('jurnal', 'JURNAL')], verbose_name='Pos Laporan*'),
        ),
    ]
