# Generated by Django 2.2.7 on 2021-01-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20210111_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='poslaporan',
            field=models.IntegerField(choices=[(0, 'NERACA'), (1, 'JURNAL')], verbose_name='Pos Laporan*'),
        ),
        migrations.AlterField(
            model_name='akun',
            name='possaldo',
            field=models.IntegerField(choices=[(0, 'DEBET'), (1, 'KREDIT')], verbose_name='Pos Saldo*'),
        ),
    ]
