# Generated by Django 2.2.7 on 2021-01-11 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210111_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ba', models.CharField(max_length=255)),
                ('nama_anggota', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=13)),
                ('nama_penjamin', models.CharField(max_length=255)),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('keterangan', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Survey'), (1, 'Anggota Baru')])),
            ],
        ),
    ]
